addons:
  apt:
    packages:
    - libxxf86vm-dev
    - libosmesa6-dev
language: rust
rust:
  - stable
  - nightly
cache: cargo
os:
  - osx
  - linux
notifications:
  webhooks: http://build.servo.org:54856/travis
env:
  - VERBOSE=1

script:
  - cargo build --no-default-features
  - cargo build